### ISSUE TITLE
Check font-smoothing usage

### ISSUE THREAD

**Issue by Plou** [dummy-team/dummy-wordpress#61]
Font-smoothing don't seem to have any effect anymore on Firefox macos.

On webkit and blink, it still do the job (safari, chrome, edge, opera).

```css
body {
  -moz-osx-font-smoothing: grayscale; // not needed
  -webkit-font-smoothing: antialiased; // still work
}
```

Some people are against its usage : https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth#See_also
(Not sure I agree)
